version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    restart: unless-stopped
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    networks:
      - sammy

networks:
  sammy:
    name: sammy-front-net
    driver: bridge